name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/html/
            cd Pendataan-Desa
            git pull origin master
            chown -R $USER:www-data storage
            chmod -R 775 storage
            composer install
